### ISSUE TITLE
Update By Query once more

### ISSUE THREAD

**Issue by DusanSenior** [RudeySH/EntityFramework.Utilities#23] opened 2019-10-17 06:31 UTC
Hi, I have similar problem as has been reported in previous issue
there is an example
(like your example EFBatchOperation.For(db, db.Comments).Where(x => x.Text == "a").Update(x => x.Reads, x => x.Reads + 1);)

var value1 = 1
var value2 = 2
EFBatchOperation.For(db, db.Comments)
.Where(x => x.Reads == value1)
.Update(x => x.Reads, x => value2);
The variable name '@p__linq__0' has already been declared... is thrown
Note: If I have used constant instead of variables all is OK
But I would like to execute parametrized sql: "update Comments set Reads = @2 where Reads = @1"
Thanks
Dusan

**Comment by RudeySH** [comment] 2022-04-02 16:49
Duplicate of #19

**Closed as completed by RudeySH** 2022-04-02 16:49 UTC
