### ISSUE TITLE
Method not found error when dropped this fork in place of original repo.

### ISSUE THREAD

**Issue by jwilliamson1** [RudeySH/EntityFramework.Utilities#8] opened 2018-04-23 19:52 UTC
`System.MissingMethodException: Method not found: 'EntityFramework.Utilities.IEFBatchOperationBase``1<!!1> EntityFramework.Utilities.EFBatchOperation.For(!!0, System.Data.Entity.IDbSet``1<!!1>)'.`

I receive this error when I built this fork and dropped it in place of the original branch.

I'm  using it like this. 

`            this.dbInsert = Task.Run(
                () =>
                {
                    EFBatchOperation.For(this.db, this.db.Changes)
                    .InsertAll(this.changes.GetConsumingEnumerable());
                });
`

Am I missing something in the build process. I just build the repo and added EntityFramework.Utilites as a reference in my project.

**Comment by RudeySH** [comment] 2018-05-26 11:21
There is a NuGet package for this fork available now. See here: https://www.nuget.org/packages/RudeySH.EFUtilities/

Could you try using this and see if the exception stops from being thrown?

**Comment by RudeySH** [comment] 2018-07-09 18:44
I have been unable to reproduce the issue. I will close this but feel free to reopen if you can provide me with detailed steps on how to reproduce this in a blank solution.

**Closed as completed by RudeySH** 2018-07-09 18:44 UTC

**Comment by jwilliamson1** [comment] 2018-07-10 14:03
Unfortunately I have been pulled from the project where I was using this, but I'll see if my colleague is interested in trying this library. Thank you!
